{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/30920",
  "id": 1572413697,
  "node_id": "I_kwDOCFbutM5duSEB",
  "number": 30920,
  "title": "Unable to create two connections to the same database with different users",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1273026509,
      "node_id": "MDU6TGFiZWwxMjczMDI2NTA5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/persistence",
      "name": "area/persistence",
      "color": "FBCA04",
      "default": false,
      "description": "OBSOLETE, DO NOT USE"
    },
    {
      "id": 2744442223,
      "node_id": "MDU6TGFiZWwyNzQ0NDQyMjIz",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/triage/needs-reproducer",
      "name": "triage/needs-reproducer",
      "color": "FDE078",
      "default": false,
      "description": "We are waiting for a reproducer."
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 3,
  "created_at": "2023-02-06T11:39:14Z",
  "updated_at": "2023-02-21T07:21:46Z",
  "closed_at": "2023-02-21T07:21:45Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nUnable to create two connections to the same database in MySQL but will different credentials. I used the named data source concept (https://quarkus.io/guides/datasource) but resulted in an error\r\n` WARN  [io.agr.pool] (agroal-11) Datasource 'app': Communications link failure`\r\n\r\napplication.properties\r\n```\r\nquarkus.datasource.\"app\".db-kind=mysql\r\nquarkus.datasource.\"app\".username=read_only_user\r\nquarkus.datasource.\"app\".password=read_only_user\r\nquarkus.datasource.\"app\".jdbc.url=<sameurl>\r\n\r\nquarkus.datasource.db-kind=mysql\r\nquarkus.datasource.username=default\r\nquarkus.datasource.password=default\r\nquarkus.datasource.jdbc.url=<sameurl>\r\n```\r\n\r\nDao layer using the \"app\" data source\r\n\r\n```\r\n@ApplicationScoped\r\npublic class Dao {\r\n\r\n  @Inject\r\n  @PersistenceUnit(\"app\")\r\n  EntityManager em;\r\n```\r\nDefault data source\r\n\r\n```\r\n @ApplicationScoped\r\n    public class Dao2 {\r\n    \r\n      @Inject\r\n      EntityManager em;\r\n```\r\n\r\n### Expected behavior\r\n\r\nTo be able to use both data sources with the same URL but different credentials in the application.\r\n\r\n### Actual behavior\r\n\r\nGetting error while trying to use the same URL and different credentials in two data sources instances \r\n`WARN  [io.agr.pool] (agroal-11) Datasource 'app': Communications link failure`\r\n\r\n### How to Reproduce?\r\n\r\nDescribed above\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\n_No response_\r\n\r\n### Output of `java -version`\r\n\r\n17\r\n\r\n### GraalVM version (if different from Java)\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n2.15.3.Final\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n3.8.1\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30920/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
