{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/38018",
  "id": 2065328134,
  "node_id": "I_kwDOCFbutM57GmgG",
  "number": 38018,
  "title": "Openshift extension fails to pull images, it creates, when quarkus.container-image.group property is used",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1654772125,
      "node_id": "MDU6TGFiZWwxNjU0NzcyMTI1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/kubernetes",
      "name": "area/kubernetes",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/303",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/303",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/303/labels",
    "id": 10462999,
    "node_id": "MI_kwDOCFbutM4An6cX",
    "number": 303,
    "title": "3.7.1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 33,
    "state": "closed",
    "created_at": "2024-01-24T13:51:37Z",
    "updated_at": "2024-01-31T17:01:26Z",
    "due_on": null,
    "closed_at": "2024-01-31T11:23:05Z"
  },
  "comments": 22,
  "created_at": "2024-01-04T09:47:08Z",
  "updated_at": "2024-01-30T18:51:05Z",
  "closed_at": "2024-01-27T17:05:55Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nI have an application, which is being deployed to openshift via `quarkus-openshift` extension. After an update to newer SNAPSHOT (somewhere between 22nd and 24th of December 2023), app fails to start on openshift and there is  \"failed to pull image\" error in openshift events. This can only be reproduced, when I use `quarkus.container-image.group` property.\n\n### Expected behavior\n\nThe application starts\n\n### Actual behavior\n\nThe application fails to start, `oc get events` contains this:\r\n\r\n\r\n```\r\nLAST SEEN   TYPE      REASON              OBJECT                     MESSAGE\r\n63s         Normal    Scheduled           pod/app-1-build            Successfully assigned fd-test/app-1-build to ocp4-14-qtbj7-worker-0-7njbr\r\n61s         Normal    AddedInterface      pod/app-1-build            Add eth0 [EDITED] from openshift-sdn\r\n61s         Normal    Pulled              pod/app-1-build            Container image \"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7207a02d23e70b9b07f01446e5cf2916b807e43b2169e35c33c668302e0842f9\" already present on machine\r\n61s         Normal    Created             pod/app-1-build            Created container git-clone\r\n61s         Normal    Started             pod/app-1-build            Started container git-clone\r\n56s         Normal    Pulled              pod/app-1-build            Container image \"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7207a02d23e70b9b07f01446e5cf2916b807e43b2169e35c33c668302e0842f9\" already present on machine\r\n56s         Normal    Created             pod/app-1-build            Created container manage-dockerfile\r\n56s         Normal    Started             pod/app-1-build            Started container manage-dockerfile\r\n55s         Normal    Pulled              pod/app-1-build            Container image \"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7207a02d23e70b9b07f01446e5cf2916b807e43b2169e35c33c668302e0842f9\" already present on machine\r\n55s         Normal    Created             pod/app-1-build            Created container sti-build\r\n55s         Normal    Started             pod/app-1-build            Started container sti-build\r\n60s         Normal    BuildStarted        build/app-1                Build fd-test/app-1 is now running\r\n41s         Normal    BuildCompleted      build/app-1                Build fd-test/app-1 completed successfully\r\n36s         Normal    Scheduled           pod/app-ff8f5d774-j26ph    Successfully assigned fd-test/app-ff8f5d774-j26ph to ocp4-14-qtbj7-worker-0-7njbr\r\n35s         Normal    AddedInterface      pod/app-ff8f5d774-j26ph    Add eth0 [EDITED] from openshift-sdn\r\n19s         Normal    Pulling             pod/app-ff8f5d774-j26ph    Pulling image \"fd-test/app:1.0.0-SNAPSHOT\"\r\n18s         Warning   Failed              pod/app-ff8f5d774-j26ph    Failed to pull image \"fd-test/app:1.0.0-SNAPSHOT\": rpc error: code = Unknown desc = reading manifest 1.0.0-SNAPSHOT in EDITED:5000/fd-test/app: manifest unknown\r\n18s         Warning   Failed              pod/app-ff8f5d774-j26ph    Error: ErrImagePull\r\n4s          Normal    BackOff             pod/app-ff8f5d774-j26ph    Back-off pulling image \"fd-test/app:1.0.0-SNAPSHOT\"\r\n4s          Warning   Failed              pod/app-ff8f5d774-j26ph    Error: ImagePullBackOff\r\n37s         Normal    SuccessfulCreate    replicaset/app-ff8f5d774   Created pod: app-ff8f5d774-j26ph\r\n37s         Normal    ScalingReplicaSet   deployment/app             Scaled up replica set app-ff8f5d774 to 1\r\n```\n\n### How to Reproduce?\n\n1. `git clone git@github.com:fedinskiy/reproducer.git -b openshift-pull-failure`\r\n2. `cd reproducer`\r\n3. `oc new-project my-project`\r\n4.  `mvn -Popenshift package -Dquarkus.container-image.group=my-project`\r\n5. `oc get events`\r\n\r\nif p.4 uses `mvn -Popenshift package` or `mvn -Popenshift package -Dquarkus.container-image.group=my-project -Dquarkus.platform.version=3.6.4`, when deployment is succesfull\n\n### Output of `uname -a` or `ver`\n\n4.18.0-513.9.1.el8_9.x86_64\n\n### Output of `java -version`\n\n11.0.21, vendor: Red Hat, Inc.\n\n### Quarkus version or git rev\n\n3e7134afddbc8dce21ae5eab538ea45d4c967acf\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nApache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)\n\n### Additional information\n\nAutomatic tests detect, that this error started no earlier, that 22nd of December (the commit was probably merged into main either in late hours of 21st or on 22nd)",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38018/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
