{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/39695",
  "id": 2207998574,
  "node_id": "I_kwDOCFbutM6Dm2Ju",
  "number": 39695,
  "title": "ERROR [io.ver.cor.htt.imp.HttpClientRequestImpl] (vert.x-eventloop-thread-1) {} Connection was closed",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1320737519,
      "node_id": "MDU6TGFiZWwxMzIwNzM3NTE5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/vertx",
      "name": "area/vertx",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "milestone": null,
  "comments": 1,
  "created_at": "2024-03-26T11:37:13Z",
  "updated_at": "2024-06-18T09:40:39Z",
  "closed_at": null,
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nI have found log entries in my log with the following message:\r\n`ERROR [io.ver.cor.htt.imp.HttpClientRequestImpl] (vert.x-eventloop-thread-1) {} Connection was closed`\r\nWhen I try to trace the error in other logs I can see no other errors. It seems like everything behaves like it should. Though I still wonder if the above message could mean something I should be worried about?\r\n\r\n[This bug](https://github.com/quarkusio/quarkus/issues/38335) seems to be very similar to my problem on a ConnectionBase instead of HttpClientRequestImpl.\r\n\r\nI am using Quarkus 3.8.1 with these dependencies:\r\n```\r\nio.quarkus:quarkus-smallrye-openapi\r\nio.quarkus:quarkus-rest-client-reactive-jackson\r\nio.quarkus:quarkus-resteasy-reactive-jackson\r\nio.quarkus:quarkus-smallrye-fault-tolerance\r\nio.quarkus:quarkus-arc\r\nio.quarkus:quarkus-smallrye-context-propagation\r\nio.quarkus:quarkus-smallrye-health\r\nio.quarkus:quarkus-opentelemetry\r\nio.opentelemetry:opentelemetry-extension-trace-propagators\r\nio.quarkus:quarkus-smallrye-jwt\r\nio.quarkus:quarkus-cache\r\n```\n\n### Expected behavior\n\nThat either there would be no error log or there would be a more descriptive error log which points me in the correct direction.\n\n### Actual behavior\n\nThis log entry is shown:\r\n`ERROR [io.ver.cor.htt.imp.HttpClientRequestImpl] (vert.x-eventloop-thread-1) {} Connection was closed`\r\nfor like it seems no particular reason.\n\n### How to Reproduce?\n\nIt doesn't seem there is a special trigger for the log entry. There are hundreds of calls per minute to this service. So there should be either a lot of entries or none. It appears randomly it seems.\n\n### Output of `uname -a` or `ver`\n\nGNU/Linux\n\n### Output of `java -version`\n\nJava 17\n\n### Quarkus version or git rev\n\nQuarkus 3.8.1\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nGradle 8.6\n\n### Additional information\n\nI know uname -a and java -version is not very specific. The code is build and deployed on a system I have no much control of. I can find more specific informations about it if it is of any importance for the issue but it might take a while because of the easter holidays.",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39695/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
